version: "3"
services:

  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    volumes:
      - mongo_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27018:27017

  server:
    container_name: Server
    build: .
    working_dir: /Backend
    volumes:
      - ./:/Backend
    ports:
      - 4000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: Banck-Of-Morroco

    depends_on:
      - mongo_db

volumes:
  mongo_db: